package the.grocery.frugal.Models;
// Generated May 30, 2019 9:42:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Recipe generated by hbm2java
 */
public class Recipe  implements java.io.Serializable {


     private int id;
     private Categories categories;
     private Integer calories;
     private Integer caloriesFat;
     private Integer cholesterol;
     private String description;
     private String name;
     private Integer saturatedFat;
     private Integer totalFat;
     private Integer transFat;
     private Integer sodium;
     private Integer totalCarb;
     private Integer dietaryFib;
     private Integer sugars;
     private Integer protein;
     private Set recipeIngredientses = new HashSet(0);

    public Recipe() {
    }

	
    public Recipe(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Recipe(int id, Categories categories, Integer calories, Integer caloriesFat, Integer cholesterol, String description, String name, Integer saturatedFat, Integer totalFat, Integer transFat, Integer sodium, Integer totalCarb, Integer dietaryFib, Integer sugars, Integer protein, Set recipeIngredientses) {
       this.id = id;
       this.categories = categories;
       this.calories = calories;
       this.caloriesFat = caloriesFat;
       this.cholesterol = cholesterol;
       this.description = description;
       this.name = name;
       this.saturatedFat = saturatedFat;
       this.totalFat = totalFat;
       this.transFat = transFat;
       this.sodium = sodium;
       this.totalCarb = totalCarb;
       this.dietaryFib = dietaryFib;
       this.sugars = sugars;
       this.protein = protein;
       this.recipeIngredientses = recipeIngredientses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public Integer getCalories() {
        return this.calories;
    }
    
    public void setCalories(Integer calories) {
        this.calories = calories;
    }
    public Integer getCaloriesFat() {
        return this.caloriesFat;
    }
    
    public void setCaloriesFat(Integer caloriesFat) {
        this.caloriesFat = caloriesFat;
    }
    public Integer getCholesterol() {
        return this.cholesterol;
    }
    
    public void setCholesterol(Integer cholesterol) {
        this.cholesterol = cholesterol;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getSaturatedFat() {
        return this.saturatedFat;
    }
    
    public void setSaturatedFat(Integer saturatedFat) {
        this.saturatedFat = saturatedFat;
    }
    public Integer getTotalFat() {
        return this.totalFat;
    }
    
    public void setTotalFat(Integer totalFat) {
        this.totalFat = totalFat;
    }
    public Integer getTransFat() {
        return this.transFat;
    }
    
    public void setTransFat(Integer transFat) {
        this.transFat = transFat;
    }
    public Integer getSodium() {
        return this.sodium;
    }
    
    public void setSodium(Integer sodium) {
        this.sodium = sodium;
    }
    public Integer getTotalCarb() {
        return this.totalCarb;
    }
    
    public void setTotalCarb(Integer totalCarb) {
        this.totalCarb = totalCarb;
    }
    public Integer getDietaryFib() {
        return this.dietaryFib;
    }
    
    public void setDietaryFib(Integer dietaryFib) {
        this.dietaryFib = dietaryFib;
    }
    public Integer getSugars() {
        return this.sugars;
    }
    
    public void setSugars(Integer sugars) {
        this.sugars = sugars;
    }
    public Integer getProtein() {
        return this.protein;
    }
    
    public void setProtein(Integer protein) {
        this.protein = protein;
    }
    public Set getRecipeIngredientses() {
        return this.recipeIngredientses;
    }
    
    public void setRecipeIngredientses(Set recipeIngredientses) {
        this.recipeIngredientses = recipeIngredientses;
    }




}


