/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thegrocery.thegroceryfrugal;

import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author user_account
 */
public class GUI extends javax.swing.JFrame {

    private List<Product> products;

    private List<Recipe> recipes;
    
    private DefaultListModel model;

    /**
     * Creates new form GUI
     */
    public GUI() {
        products = new ArrayList<>();
        recipes = new ArrayList<>();
        initComponents();
        
        model = new DefaultListModel();
        listRecipes.setModel(model);

        cbRecipes.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent me) {
                Recipe r = (Recipe) cbRecipes.getSelectedItem();
                if (r != null) {
                    cbRecipes.setToolTipText("<html>" + r.toString() + "</html>");
                }
            }
        });

        setLocationRelativeTo(null);
    }

    public void updateProducts(List<Product> products) {
        cbProducts.removeAllItems();
        products.forEach(p -> cbProducts.addItem(p));
    }

    public void updateRecipes(List<Recipe> recipes) {
        cbRecipes.removeAllItems();
        recipes.forEach(r -> cbRecipes.addItem(r));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbRecipes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbProducts = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnAddGroceryList = new javax.swing.JButton();
        btnSearchRecipte = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnAddProduct = new javax.swing.JButton();
        btnCreateRecipe = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listRecipes = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        tfIngredient = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Recipes:");

        jLabel3.setText("Products:");

        btnAddGroceryList.setText("Add To Grocery List");
        btnAddGroceryList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGroceryListActionPerformed(evt);
            }
        });

        btnSearchRecipte.setText("Search Recipe");
        btnSearchRecipte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRecipteActionPerformed(evt);
            }
        });

        jLabel4.setText("Grocery list:");

        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnCreateRecipe.setText("Create Recipe");
        btnCreateRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRecipeActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listRecipes);

        jLabel2.setText("Enter ingredient:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSearchRecipte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfIngredient))))
                                .addGap(60, 60, 60))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAddGroceryList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCreateRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProducts, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddGroceryList)
                    .addComponent(btnAddProduct)
                    .addComponent(btnCreateRecipe))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchRecipte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddGroceryListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGroceryListActionPerformed
        Recipe recipe = (Recipe) cbRecipes.getSelectedItem();
        if (recipe == null) {
            JOptionPane.showMessageDialog(this, "Select recipe!", "Failed", JOptionPane.ERROR_MESSAGE);
        } else {
            model.addElement(recipe.toString().replaceAll("<br>", ""));
        }
    }//GEN-LAST:event_btnAddGroceryListActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        JTextField tfName = new JTextField(10);
        JSpinner jsQuantity = new JSpinner(new SpinnerNumberModel(1, 1, 10, 1));
        JPanel pnl = new JPanel();
        pnl.add(new JLabel("Enter product name:"));
        pnl.add(tfName);
        pnl.add(new JLabel("Select quantity:"));
        pnl.add(jsQuantity);
        JOptionPane.showMessageDialog(this, pnl);
        String name = tfName.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Empty name!", "Failed", JOptionPane.ERROR_MESSAGE);
        } else {
            Product product = new Product(name, (int) jsQuantity.getValue());
            products.add(product);
            updateProducts(products);
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnSearchRecipteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRecipteActionPerformed
        String ingredient = tfIngredient.getText().trim();

        List<Recipe> result = new ArrayList<>(recipes);
        result.removeIf(r -> !r.toString().contains(ingredient));
        updateRecipes(result);
    }//GEN-LAST:event_btnSearchRecipteActionPerformed

    private void btnCreateRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRecipeActionPerformed
        int numProducts = products.size();
        JPanel pnl = new JPanel(new GridLayout(numProducts, 2));
        List<JSpinner> quantities = new ArrayList<>();
        for (Product p : products) {
            pnl.add(new JLabel(p.toString()));
            JSpinner jsQuantity;
            pnl.add(jsQuantity = new JSpinner(new SpinnerNumberModel(0, 0, p.getQuantity(), 1)));
            quantities.add(jsQuantity);
        }
        JOptionPane.showMessageDialog(this, pnl);
        Recipe recipe = new Recipe();
        for (int i = 0; i < numProducts; i++) {
            int quant = (int) quantities.get(i).getValue();
            if (quant > 0) { // 0 means this product is not selected.
                Product p = (Product) cbProducts.getSelectedItem();
                recipe.addIngredient(p, quant);

            }
        }
        recipes.add(recipe);
        if (recipe.isEmpty()) {
            JOptionPane.showMessageDialog(this, "You must select at least 1 product!",
                    "Failed", JOptionPane.ERROR_MESSAGE);
        } else {
            updateRecipes(recipes);
        }
    }//GEN-LAST:event_btnCreateRecipeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGroceryList;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCreateRecipe;
    private javax.swing.JButton btnSearchRecipte;
    private javax.swing.JComboBox<Product> cbProducts;
    private javax.swing.JComboBox<Recipe> cbRecipes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Recipe> listRecipes;
    private javax.swing.JTextField tfIngredient;
    // End of variables declaration//GEN-END:variables
}
