/**
 * File: Categories.java
 * Author: hbm2java
 * Date: 6/4/2019
 */
package com.thegrocery.thegroceryfrugal.Models;
// Generated Jun 4, 2019 6:31:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Represents Category entity.
 * <p>
 * Categories generated by hbm2java.
 */
@Entity
@Table(name = "categories")
public class Categories implements java.io.Serializable {

    /**
     * An auto-generated category ID.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, unique = true)
    private int id;

    /**
     * Description of this category.
     */
    @Column(name = "description")
    private String description;

    /**
     * Set of all recipes in this category.
     */
    @OneToMany(mappedBy = "categories")
    private Set<Recipe> recipes = new HashSet(0);

    /**
     * Constructs default Categories object.
     */
    public Categories() {
    }

    /**
     * Constructs a Categories object with the specified id.
     *
     * @param id the category ID.
     */
    public Categories(int id) {
        this.id = id;
    }

    /**
     * Constructs a Categories object with the specified properties.
     *
     * @param id          the category ID.
     * @param description the category description.
     * @param recipes     an set of recipes.
     */
    public Categories(int id, String description, Set recipes) {
        this.id = id;
        this.description = description;
        this.recipes = recipes;
    }

    /**
     * Returns the category ID.
     *
     * @return the category ID
     */
    public int getId() {
        return this.id;
    }

    /**
     * Sets the category ID.
     *
     * @param id the category ID
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the category description.
     *
     * @return the category description
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the category description.
     *
     * @param description the category description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the set containing all recipes in this category.
     *
     * @return an set of all recipes
     */
    public Set getRecipes() {
        return this.recipes;
    }

    /**
     * Sets a new set of recipes.
     *
     * @param recipes an set of recipes.
     */
    public void setRecipes(Set recipes) {
        this.recipes = recipes;
    }

    /**
     * Adds one recipe in this category.
     *
     * @param recipe a recipe
     */
    public void addRecipe(Recipe recipe) {
        recipes.add(recipe);
        recipe.setCategories(this);
    }

    /**
     * Removes one recipe from this category.
     *
     * @param recipe a recipe
     */
    public void removeRecipe(Recipe recipe) {
        recipes.remove(recipe);
        recipe.setCategories(null);
    }

    /**
     * Returns a string representation of the Category object in form "id".
     *
     * @return a string representation of the object
     */
    @Override
    public String toString() {
        return id + "";
    }
}