/**
 * File: Ingredients.java
 * Author: hbm2java
 * Date: 6/4/2019
 */
package com.thegrocery.thegroceryfrugal.Models;
// Generated Jun 1, 2019 4:17:22 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Represents ingredient entity.
 * <p>
 * Ingredients generated by hbm2java
 */
@Entity
@Table(name = "ingredients")
public class Ingredients implements java.io.Serializable {

    /**
     * An auto-generated ingredient ID.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, unique = true)
    private int id;

    /**
     * Ingredient name.
     */
    @Column(name = "name")
    private String name;

    /**
     * Ingredient description.
     */
    @Column(name = "description")
    private String description;

    /**
     * A set of recipe ingredients.
     */
    @OneToMany(mappedBy = "ingredients")
    private Set<RecipeIngredients> recipeIngredientses = new HashSet(0);

    /**
     * Constructs default Ingredients object.
     */
    public Ingredients() {
    }

    /**
     * Constructs an Ingredients object with the specified properties.
     *
     * @param name a name
     */
    public Ingredients(String name) {
        this.name = name;
    }

    /**
     * Constructs an Ingredients object with the specified properties.
     *
     * @param id   an ID
     * @param name a name
     */
    public Ingredients(int id, String name) {
        this.id = id;
        this.name = name;
    }

    /**
     * Constructs an Ingredients object with the specified properties.
     *
     * @param id                  an ID
     * @param name                a name
     * @param description         a description
     * @param recipeIngredientses a set of recipe ingredients
     */
    public Ingredients(int id, String name, String description, Set recipeIngredientses) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.recipeIngredientses = recipeIngredientses;
    }

    /**
     * Returns the ID.
     *
     * @return the ID
     */
    public int getId() {
        return this.id;
    }

    /**
     * Sets an ID.
     *
     * @param id the ID
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns an ingredient name.
     *
     * @return an ingredient name
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets an ingredient name.
     *
     * @param name an ingredient name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns an ingredient description.
     *
     * @return an ingredient description
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets an ingredient description.
     *
     * @param description an ingredient description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns a set of recipe ingredients.
     *
     * @return a set of recipe ingredients
     */
    public Set getRecipeIngredientses() {
        return this.recipeIngredientses;
    }

    /**
     * Sets a set of recipe ingredients.
     *
     * @param recipeIngredientses a set of recipe ingredients
     */
    public void setRecipeIngredientses(Set recipeIngredientses) {
        this.recipeIngredientses = recipeIngredientses;
    }

    /**
     * Adds one recipe ingredients
     *
     * @param recipeIngredients a recipe ingredients
     */
    public void addRecipeIngredients(RecipeIngredients recipeIngredients) {
        recipeIngredientses.add(recipeIngredients);
        recipeIngredients.setIngredients(this);
    }

    /**
     * Removes one recipe ingredients.
     *
     * @param recipeIngredients a recipe ingredients
     */
    public void removeRecipeIngredients(RecipeIngredients recipeIngredients) {
        recipeIngredientses.remove(recipeIngredients);
        recipeIngredients.setIngredients(null);
    }

    /**
     * Returns a string representation of the Ingredients object in form "name".
     *
     * @return a string representation of the object
     */
    @Override
    public String toString() {
        return this.getName() + "\n";
    }

}