/**
 * File: Measurement.java
 * Author: hbm2java
 * Date: 6/4/2019
 */
package com.thegrocery.thegroceryfrugal.Models;
// Generated Jun 4, 2019 6:31:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Represents Measurement entity.
 * <p>
 * Measurement generated by hbm2java
 */
@Entity
@Table(name = "measurement")
public class Measurement implements java.io.Serializable {

    /**
     * An auto-generated measurement ID.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * Measurement name.
     */
    @Column(name = "name")
    private String name;

    /**
     * A set of recipe ingredients.
     */
    @OneToMany(mappedBy = "measurement")
    private Set<RecipeIngredients> recipeIngredientses = new HashSet(0);

    /**
     * Constructs default Measurement object.
     */
    public Measurement() {
    }

    /**
     * Constructs a Measurement object with the specified name.
     *
     * @param name a name
     */
    public Measurement(String name) {
        this.name = name;
    }

    /**
     * Constructs a Measurement object with the specified properties.
     *
     * @param id   an ID
     * @param name a name
     */
    public Measurement(int id, String name) {
        this.id = id;
        this.name = name;
    }

    /**
     * Constructs a Measurement object with the specified properties.
     *
     * @param id                  an ID
     * @param name                a name
     * @param recipeIngredientses a set of recipe ingredients
     */
    public Measurement(int id, String name, Set recipeIngredientses) {
        this.id = id;
        this.name = name;
        this.recipeIngredientses = recipeIngredientses;
    }

    /**
     * Returns measurement ID.
     *
     * @return the measurement ID
     */
    public int getId() {
        return this.id;
    }

    /**
     * Sets measurement ID.
     *
     * @param id the measurement ID.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns measurement name.
     *
     * @return the measurement name
     */
    public String getName() {
        return this.name.substring(0, 1).toUpperCase() + this.name.substring(1);
    }

    /**
     * Sets measurement name
     *
     * @param name the measurement name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns a set of recipe ingredients.
     *
     * @return a set of recipe ingredients
     */
    public Set getRecipeIngredientses() {
        return this.recipeIngredientses;
    }

    /**
     * Sets a set of recipe ingredients.
     *
     * @param recipeIngredientses a set of recipe ingredients
     */
    public void setRecipeIngredientses(Set recipeIngredientses) {
        this.recipeIngredientses = recipeIngredientses;
    }

    /**
     * Adds one recipe ingredients
     *
     * @param recipeIngredients a recipe ingredients
     */
    public void addRecipeIngredients(RecipeIngredients recipeIngredients) {
        recipeIngredientses.add(recipeIngredients);
        recipeIngredients.setMeasurement(this);
    }

    /**
     * Removes one recipe ingredients.
     *
     * @param recipeIngredients a recipe ingredients
     */
    public void removeRecipeIngredients(RecipeIngredients recipeIngredients) {
        recipeIngredientses.remove(recipeIngredients);
        recipeIngredients.setMeasurement(null);
    }
}