/**
 * File: Nutrition.java
 * Author: hbm2java
 * Date: 6/4/2019
 */
package com.thegrocery.thegroceryfrugal.Models;
// Generated Jun 4, 2019 6:31:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Represents Nutrition entity.
 * <p>
 * Nutrition generated by hbm2java
 */
@Entity
@Table(name = "nutrition")
public class Nutrition implements java.io.Serializable {

    /**
     * An auto-generated Nutrition ID.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, unique = true)
    private long id;

    /**
     * Calories.
     */
    @Column(name = "calories")
    private String calories;

    /**
     * Calories Fat.
     */
    @Column(name = "calories_fat")
    private String caloriesFat;

    /**
     * Cholesterol.
     */
    @Column(name = "cholesterol")
    private String cholesterol;

    /**
     * Saturated Fat.
     */
    @Column(name = "saturated_fat")
    private String saturatedFat;

    /**
     * Total Fat.
     */
    @Column(name = "total_fat")
    private String totalFat;

    /**
     * Trans Fat.
     */
    @Column(name = "trans_fat")
    private String transFat;

    /**
     * Sodium.
     */
    @Column(name = "sodium")
    private String sodium;

    /**
     * Total Carbons.
     */
    @Column(name = "total_carb")
    private String totalCarb;

    /**
     * Dietary Fiber
     */
    @Column(name = "dietary_fib")
    private String dietaryFib;

    /**
     * Sugars.
     */
    @Column(name = "sugars")
    private String sugars;

    /**
     * Protein.
     */
    @Column(name = "protein")
    private String protein;

    /**
     * Recipe.
     */
    @OneToOne(mappedBy = "nutrition")
    private Recipe recipe;

    /**
     * Constructs default Nutrition object.
     */
    public Nutrition() {
    }

    /**
     * Constructs a Nutrition object with the specified id.
     *
     * @param id the ID.
     */
    public Nutrition(long id) {
        this.id = id;
    }

    /**
     * Constructs a Nutrition object with the specified properties.
     *
     * @param id           ID
     * @param calories     Calories
     * @param caloriesFat  Calories Fats
     * @param cholesterol  Cholesterol
     * @param saturatedFat Saturated Fats
     * @param totalFat     Total Fat
     * @param transFat     TransFat
     * @param sodium       Sodium
     * @param totalCarb    Total Carbons
     * @param dietaryFib   Dietary Fibers
     * @param sugars       Sugars
     * @param protein      Protein
     * @param recipe       Recipe
     */
    public Nutrition(long id, String calories, String caloriesFat, String cholesterol, String saturatedFat,
                     String totalFat, String transFat, String sodium, String totalCarb, String dietaryFib, String sugars,
                     String protein, Recipe recipe) {
        this.id = id;
        this.calories = calories;
        this.caloriesFat = caloriesFat;
        this.cholesterol = cholesterol;
        this.saturatedFat = saturatedFat;
        this.totalFat = totalFat;
        this.transFat = transFat;
        this.sodium = sodium;
        this.totalCarb = totalCarb;
        this.dietaryFib = dietaryFib;
        this.sugars = sugars;
        this.protein = protein;
        this.recipe = recipe;
    }

    /**
     * Returns nutrition ID.
     *
     * @return nutrition ID
     */
    public long getId() {
        return this.id;
    }

    /**
     * Sets nutrition ID.
     *
     * @param id nutrition ID
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns a calories.
     *
     * @return a calories
     */
    public String getCalories() {
        return this.calories;
    }

    /**
     * Sets a calories.
     *
     * @param calories a calories
     */
    public void setCalories(String calories) {
        this.calories = calories;
    }

    /**
     * Returns a Calories Fat.
     *
     * @return a Calories Fat
     */
    public String getCaloriesFat() {
        return this.caloriesFat;
    }

    /**
     * Sets a Calories Fat
     *
     * @param caloriesFat a Calories Fat
     */
    public void setCaloriesFat(String caloriesFat) {
        this.caloriesFat = caloriesFat;
    }

    /**
     * Returns a Cholesterol.
     *
     * @return a Cholesterol
     */
    public String getCholesterol() {
        return this.cholesterol;
    }

    /**
     * Sets a Cholesterol.
     *
     * @param cholesterol a Cholesterol
     */
    public void setCholesterol(String cholesterol) {
        this.cholesterol = cholesterol;
    }

    /**
     * Returns a Saturated Fat.
     *
     * @return a Saturated Fat
     */
    public String getSaturatedFat() {
        return this.saturatedFat;
    }

    /**
     * Sets a Saturated Fat.
     *
     * @param saturatedFat a Saturated Fat
     */
    public void setSaturatedFat(String saturatedFat) {
        this.saturatedFat = saturatedFat;
    }

    /**
     * Returns a Total Fat.
     *
     * @return a Total Fat
     */
    public String getTotalFat() {
        return this.totalFat;
    }

    /**
     * Sets a Total Fat.
     *
     * @param totalFat a Total Fat
     */
    public void setTotalFat(String totalFat) {
        this.totalFat = totalFat;
    }

    /**
     * Returns a TransFat.
     *
     * @return a TransFat
     */
    public String getTransFat() {
        return this.transFat;
    }

    /**
     * Sets a TransFat.
     *
     * @param transFat a TransFat
     */
    public void setTransFat(String transFat) {
        this.transFat = transFat;
    }

    /**
     * Returns a Sodium.
     *
     * @return a Sodium
     */
    public String getSodium() {
        return this.sodium;
    }

    /**
     * Sets a Sodium.
     *
     * @param sodium a Sodium
     */
    public void setSodium(String sodium) {
        this.sodium = sodium;
    }

    /**
     * Returns a Total Carbons.
     *
     * @return a Total Carbons
     */
    public String getTotalCarb() {
        return this.totalCarb;
    }

    /**
     * Sets a Total Carbons.
     *
     * @param totalCarb a Total Carbons
     */
    public void setTotalCarb(String totalCarb) {
        this.totalCarb = totalCarb;
    }

    /**
     * Returns a Dietary Fibers.
     *
     * @return a Dietary Fibers
     */
    public String getDietaryFib() {
        return this.dietaryFib;
    }

    /**
     * Sets a Dietary Fibers.
     *
     * @param dietaryFib a Dietary Fibers
     */
    public void setDietaryFib(String dietaryFib) {
        this.dietaryFib = dietaryFib;
    }

    /**
     * Returns a Sugars.
     *
     * @return a Sugars
     */
    public String getSugars() {
        return this.sugars;
    }

    /**
     * Sets a Sugars.
     *
     * @param sugars a Sugars
     */
    public void setSugars(String sugars) {
        this.sugars = sugars;
    }

    /**
     * Returns a Protein.
     *
     * @return a Protein
     */
    public String getProtein() {
        return this.protein;
    }

    /**
     * Sets a Protein.
     *
     * @param protein a Protein
     */
    public void setProtein(String protein) {
        this.protein = protein;
    }

    /**
     * Returns a recipe.
     *
     * @return a recipe
     */
    public Recipe getRecipes() {
        return this.recipe;
    }

    /**
     * Sets a recipe.
     *
     * @param recipe a recipe
     */
    public void setRecipes(Recipe recipe) {
        this.recipe = recipe;
    }

    /**
     * Returns a string representation of the Nutrition object in form "id".
     *
     * @return a string representation of the object
     */
    @Override
    public String toString() {
        return String.format("%i", id);
    }

}