package com.thegrocery.thegroceryfrugal.Models;
// Generated Jun 4, 2019 6:31:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Recipe generated by hbm2java
 */
@Entity
@Table(name = "recipe")
public class Recipe implements java.io.Serializable {

    /**
     * An auto-generated recipe ID.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private int id;

    /**
     * Category.
     */
    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "category_id")
    private Categories categories;

    /**
     * Nutrition.
     */
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "nutrition_id", referencedColumnName = "id")
    private Nutrition nutrition;

    /**
     * A description.
     */
    @Column(name = "description")
    private String description;

    /**
     * Name.
     */
    @Column(name = "name")
    private String name;

    /**
     * Steps.
     */
    @Column(name = "steps")
    private String steps;

    /**
     * A set of recipe ingredients.
     */
    @OneToMany(mappedBy = "recipe")
    private Set<RecipeIngredients> recipeIngredientses = new HashSet(0);

    /**
     * An user.
     */
    
    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "user_id")
    private Users user;

    /**
     * Constructs default Recipe object.
     */
    public Recipe() {

    }

    /**
     * Constructs a Recipe object with the specified properties.
     *
     * @param name a name
     * @param user an user
     */
    public Recipe(String name, Users user) {
        this.name = name;
        this.user = user;
    }

    /**
     * Constructs a Recipe object with the specified properties.
     *
     * @param name        a name
     * @param description a description
     * @param user        a user
     */
    public Recipe(String name, String description, Users user) {
        this.name = name;
        this.description = description;
        this.user = user;
    }

    /**
     * Constructs a Recipe object with the specified properties.
     *
     * @param name        a name
     * @param description a description
     * @param steps       a steps
     * @param user        an user
     */
    public Recipe(String name, String description, String steps, Users user) {
        this.name = name;
        this.description = description;
        this.steps = steps;
        this.user = user;
    }

    /**
     * Constructs a Recipe object with the specified properties.
     *
     * @param name        a name
     * @param category    a category
     * @param description a description
     * @param steps       a steps
     * @param user        a user
     */
    public Recipe(String name, Categories category, String description, String steps, Users user) {
        this.name = name;
        this.categories = category;
        this.description = description;
        this.steps = steps;
        this.user = user;
    }

    /**
     * Constructs a Recipe object with the specified properties.
     *
     * @param categories          a category
     * @param nutrition           a nutrition
     * @param description         a description
     * @param name                a name
     * @param steps               a steps
     * @param recipeIngredientses a set of recipe ingredients
     */
    public Recipe(Categories categories, Nutrition nutrition, String description, String name, String steps, Set recipeIngredientses) {
        this.categories = categories;
        this.nutrition = nutrition;
        this.description = description;
        this.name = name;
        this.steps = steps;
        this.recipeIngredientses = recipeIngredientses;
    }

    /**
     * Returns recipe ID.
     *
     * @return a recipe ID
     */
    public int getId() {
        return this.id;
    }

    /**
     * Sets recipe ID.
     *
     * @param id a recipe ID
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns a category.
     *
     * @return a category
     */
    public Categories getCategories() {
        return this.categories;
    }

    /**
     * Sets a category.
     *
     * @param categories a category
     */
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

    /**
     * Returns a nutrition.
     *
     * @return a nutrition
     */
    public Nutrition getNutrition() {
        return this.nutrition;
    }

    /**
     * Sets a nutrition.
     *
     * @param nutrition a nutrition
     */
    public void setNutrition(Nutrition nutrition) {
        this.nutrition = nutrition;
    }

    /**
     * Returns the description.
     *
     * @return the description
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the description.
     *
     * @param description the description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the name.
     *
     * @return the name
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets the name.
     *
     * @param name the name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns a number of steps.
     *
     * @return a number of steps
     */
    public String getSteps() {
        return this.steps;
    }

    /**
     * Sets a number of steps.
     *
     * @param steps a number of steps
     */
    public void setSteps(String steps) {
        this.steps = steps;
    }

    /**
     * Returns the user.
     *
     * @return the user
     */
    public Users getUser() {
        return user;
    }

    /**
     * Sets the user.
     *
     * @param user the user
     */
    public void setUser(Users user) {
        this.user = user;
    }

    /**
     * Returns a set of recipe ingredients.
     *
     * @return a set of recipe ingredients
     */
    public Set getRecipeIngredientses() {
        return this.recipeIngredientses;
    }

    /**
     * Sets a set of recipe ingredients.
     *
     * @param recipeIngredientses a set of recipe ingredients
     */
    @SuppressWarnings("unchecked")
    public void setRecipeIngredientses(Set recipeIngredientses) {
        this.recipeIngredientses = recipeIngredientses;
    }

    /**
     * Adds one recipe ingredients
     *
     * @param recipeIngredients a recipe ingredients
     */
    public void addRecipeIngredients(RecipeIngredients recipeIngredients) {
        recipeIngredientses.add(recipeIngredients);
        recipeIngredients.setRecipe(this);
    }

    /**
     * Removes one recipe ingredients.
     *
     * @param recipeIngredients a recipe ingredients
     */
    public void removeRecipeIngredients(RecipeIngredients recipeIngredients) {
        recipeIngredientses.remove(recipeIngredients);
        recipeIngredients.setRecipe(null);
    }
    
    public String toString(Transaction tx, Session session){
        String string = "";
        
        string = this.getName() + "\n";
        string += "Creator: " + this.getUser().getUsername() + "\n\n";
        
        try{
            Recipe recipe = (Recipe) session.createQuery("SELECT R FROM Recipe R JOIN FETCH R.recipeIngredientses RI WHERE RI.recipe = " + this.getId()).uniqueResult();
            Set<RecipeIngredients> recipeIngredients = recipe.getRecipeIngredientses();
            string += "Ingredients: \n";
            string += "Ingredient\tQuantity\tUnit\tDescription\n";
            for (Iterator iter = recipeIngredients.iterator(); iter.hasNext();){
                RecipeIngredients RI = (RecipeIngredients)iter.next();
                if (RI.getDescription() == null || RI.getDescription() == "null"){
                    string += RI.getIngredients().getName() + "\t" + RI.getMeasurement().getName() + "\t" + RI.getQuantity() + "\n";
                } else {
                    string += RI.getIngredients().getName() + "\t" + RI.getMeasurement().getName() + "\t" + RI.getQuantity() + "\t" + RI.getDescription() + "\n";
                }
                
            }
        } catch (NullPointerException ex){
            string += "Ingredients:\n   (No ingredients found. You can add ingredients with the 'Modify Existing' button.)\n";
        }
            
        string += "\nSteps: \n";
        if (this.getSteps() == null || this.getSteps() == "null"){
            string += "No steps found for this recipe\n";
        } else {
            string += this.getSteps();
        }
        
        string += "\n-----------------------------------------------------------\n";
        return string;
    }
    
    @Override
    public String toString() {
    	return name;
    }

}
