/**
 * File: RecipeIngredients.java
 * Author: hbm2java
 * Date: 6/4/2019
 */
package com.thegrocery.thegroceryfrugal.Models;
// Generated Jun 4, 2019 6:31:11 AM by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.ManyToOne;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Table;

/**
 * Represents RecipeIngredients entity.
 * <p>
 * RecipeIngredients generated by hbm2java
 */
@Entity
@Table(name = "recipe_ingredients")
public class RecipeIngredients implements java.io.Serializable {

    /**
     * An auto-generated recipe ingredient ID.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, unique = true)
    private int id;

    /**
     * Recipe ingredient.
     */
    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "ingredients_id")
    private Ingredients ingredients;

    /**
     * Measurement.
     */
    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "quantity_id")
    private Measurement measurement;

    /**
     * Recipe.
     */
    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "recipe_id")
    private Recipe recipe;

    /**
     * Quantity.
     */
    private Float quantity;

    /**
     * Description.
     */
    private String description;

    /**
     * Constructs default RecipeIngredients object.
     */
    public RecipeIngredients() {
    }

    /**
     * Constructs a RecipeIngredients object with the specified properties.
     *
     * @param ingredients an ingredients
     * @param measurement a measurement
     * @param recipe      a recipe
     */
    public RecipeIngredients(Ingredients ingredients, Measurement measurement, Recipe recipe) {
        this.ingredients = ingredients;
        this.measurement = measurement;
        this.recipe = recipe;
    }

    /**
     * Constructs a RecipeIngredients object with the specified properties.
     *
     * @param ingredients an ingredients
     * @param measurement a measurement
     * @param recipe      a recipe
     * @param quantity    a quantity
     */
    public RecipeIngredients(Ingredients ingredients, Measurement measurement, Recipe recipe, Float quantity) {
        this.ingredients = ingredients;
        this.measurement = measurement;
        this.recipe = recipe;
        this.quantity = quantity;
    }

    /**
     * Constructs a RecipeIngredients object with the specified properties.
     *
     * @param ingredients an ingredients
     * @param measurement a measurement
     * @param recipe      a recipe
     * @param quantity    a quantity
     * @param description a description
     */
    public RecipeIngredients(Ingredients ingredients, Measurement measurement, Recipe recipe, Float quantity, String description) {
        this.ingredients = ingredients;
        this.measurement = measurement;
        this.recipe = recipe;
        this.quantity = quantity;
        this.description = description;
    }

    /**
     * Constructs a RecipeIngredients object with the specified properties.
     *
     * @param id          an ID
     * @param ingredients an ingredients
     * @param measurement a measurement
     * @param recipe      a recipe
     */
    public RecipeIngredients(int id, Ingredients ingredients, Measurement measurement, Recipe recipe) {
        this.id = id;
        this.ingredients = ingredients;
        this.measurement = measurement;
        this.recipe = recipe;
    }

    /**
     * Constructs a RecipeIngredients object with the specified properties.
     *
     * @param id          an ID
     * @param ingredients an ingredients
     * @param measurement a measurement
     * @param recipe      a recipe
     * @param quantity    a quantity
     * @param description a description
     */
    public RecipeIngredients(int id, Ingredients ingredients, Measurement measurement, Recipe recipe, Float quantity, String description) {
        this.id = id;
        this.ingredients = ingredients;
        this.measurement = measurement;
        this.recipe = recipe;
        this.quantity = quantity;
        this.description = description;
    }

    /**
     * Returns the ID.
     *
     * @return the ID
     */
    public int getId() {
        return this.id;
    }

    /**
     * Sets the ID.
     *
     * @param id the ID
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns an ingredients.
     *
     * @return an ingredients
     */
    public Ingredients getIngredients() {
        return this.ingredients;
    }

    /**
     * Sets an ingredients.
     *
     * @param ingredients an ingredients
     */
    public void setIngredients(Ingredients ingredients) {
        this.ingredients = ingredients;
    }

    /**
     * Returns a measurement.
     *
     * @return a measurement
     */
    public Measurement getMeasurement() {
        return this.measurement;
    }

    /**
     * Sets a measurement.
     *
     * @param measurement a measurement
     */
    public void setMeasurement(Measurement measurement) {
        this.measurement = measurement;
    }

    /**
     * Returns a recipe.
     *
     * @return a recipe
     */
    public Recipe getRecipe() {
        return this.recipe;
    }

    /**
     * Sets a recipe.
     *
     * @param recipe a recipe
     */
    public void setRecipe(Recipe recipe) {
        this.recipe = recipe;
    }

    /**
     * Returns a quantity.
     *
     * @return a quantity
     */
    public Float getQuantity() {
        return this.quantity;
    }

    /**
     * Sets a quantity.
     *
     * @param quantity a quantity
     */
    public void setQuantity(Float quantity) {
        this.quantity = quantity;
    }

    /**
     * Returns a description.
     *
     * @return a description
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets a description.
     *
     * @param description a description
     */
    public void setDescription(String description) {
        this.description = description;
    }
}