package com.thegrocery.thegroceryfrugal.GUI;

import javax.transaction.Transactional.TxType;

import com.thegrocery.thegroceryfrugal.Models.Measurement;
import com.thegrocery.thegroceryfrugal.Utility.MeasurementUtility;

public class NewGroceryList extends javax.swing.JFrame {

	public NewGroceryList() {
		initComponents();
	}

	public NewGroceryList(Measurement measurement) {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		listTitle = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		yesRadBtn = new javax.swing.JRadioButton();
		noRadBtn = new javax.swing.JRadioButton();
		newListBtn = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		DisplayPanel = new javax.swing.JTextPane();
		jLabel4 = new javax.swing.JLabel();
		ItemField = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		quantityField = new javax.swing.JTextField();
		addItemBtn = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("New Grocery List");

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
		jLabel1.setText("List Title:");

		listTitle.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				listTitleActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
		jLabel2.setText("Would you like to pull ingredients from a recipe?");

		yesRadBtn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
		yesRadBtn.setText("Yes");
		yesRadBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				yesRadBtnActionPerformed(evt);
			}
		});

		noRadBtn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
		noRadBtn.setText("No");
		noRadBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				noRadBtnActionPerformed(evt);
			}
		});

		newListBtn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
		newListBtn.setText("Save List");
		newListBtn.setToolTipText("");
		newListBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				newListBtnActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
		jLabel3.setText("List Display");

		jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		jScrollPane1.setViewportView(DisplayPanel);

		jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
		jLabel4.setText("Item:");

		ItemField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
		ItemField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ItemFieldActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
		jLabel5.setText("Quantity:");

		quantityField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
		quantityField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				quantityFieldActionPerformed(evt);
			}
		});

		addItemBtn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
		addItemBtn.setText("Add Item");
		addItemBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addItemBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(39, 39, 39)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel1).addGap(18, 18, 18)
										.addComponent(listTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 199,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(44, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(newListBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addGap(157, 157, 157)
												.addComponent(jLabel6))
										.addGroup(layout.createSequentialGroup().addGap(26, 26, 26)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel5).addComponent(jLabel4))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(ItemField, javax.swing.GroupLayout.DEFAULT_SIZE,
																187, Short.MAX_VALUE)
														.addComponent(quantityField)))
										.addGroup(layout.createSequentialGroup().addGap(25, 25, 25)
												.addComponent(jLabel2)))
										.addGap(9, 9, 9)))
								.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addGap(52, 52, 52).addComponent(yesRadBtn)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(noRadBtn).addGap(94, 94, 94))))
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(136, 136, 136).addComponent(addItemBtn))
								.addGroup(layout.createSequentialGroup().addGap(155, 155, 155).addComponent(jLabel3)))
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(listTitle, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(11, 11, 11).addComponent(jLabel2)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(yesRadBtn)
						.addComponent(noRadBtn))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel3)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
						.addComponent(ItemField, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5)
						.addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(addItemBtn)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jLabel6).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(newListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(19, 19, 19)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void listTitleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_listTitleActionPerformed
		// allows user to add list title
	}// GEN-LAST:event_listTitleActionPerformed

	private void yesRadBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_yesRadBtnActionPerformed
		// specifies if user is updating a current list. If yes, list selection action
		// must occur allowing the user to select the list to update
	}// GEN-LAST:event_yesRadBtnActionPerformed

	private void noRadBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_noRadBtnActionPerformed
		// specifies if user is not updating a current list and creating an entirely new
		// one, which will need to be added to database
	}// GEN-LAST:event_noRadBtnActionPerformed

	private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addItemBtnActionPerformed
		// allows user to add item and quantity
	}// GEN-LAST:event_addItemBtnActionPerformed

	private void ItemFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ItemFieldActionPerformed
		// input item name
	}// GEN-LAST:event_ItemFieldActionPerformed

	private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_quantityFieldActionPerformed
		// input item quantity
	}// GEN-LAST:event_quantityFieldActionPerformed

	private void newListBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newListBtnActionPerformed
		// creates new list or updates existing list
		MeasurementUtility.addMeasurement(listTitle.getText());
		dispose();

	}// GEN-LAST:event_newListBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NewGroceryList.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NewGroceryList.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NewGroceryList.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NewGroceryList.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NewGroceryList().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextPane DisplayPanel;
	private javax.swing.JTextField ItemField;
	private javax.swing.JButton addItemBtn;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField listTitle;
	private javax.swing.JButton newListBtn;
	private javax.swing.JRadioButton noRadBtn;
	private javax.swing.JTextField quantityField;
	private javax.swing.JRadioButton yesRadBtn;
	// End of variables declaration//GEN-END:variables
}
