/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thegrocery.thegroceryfrugal.GUI;
/**
 *
 * @author Mila
 */
public class NewIngredient extends javax.swing.JFrame {

    /**
     * Creates new form NewIngredient
     */
    public NewIngredient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Ingredient");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Choose ingredient from results:");

        quantityLbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        quantityLbl.setText("Quantity:");

        quantityField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });

        typeLbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        typeLbl.setText("Quantity Type:");

        typeDropDown.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        typeDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cups", "Fluid Ounces", "Grams", "Ounces", "Pounds", "Tablespoon", "Teaspoon" }));
        typeDropDown.setToolTipText("");
        typeDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeDropDownActionPerformed(evt);
            }
        });

        notesLbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        notesLbl.setText("Notes:");

        notesField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        notesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesFieldActionPerformed(evt);
            }
        });

        addToRecipeBtn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        addToRecipeBtn.setText("Add to Recipe");
        addToRecipeBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addToRecipeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToRecipeBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.setNextFocusableComponent(jScrollPane1);

        buttonGroup.add(jRadBtn1);
        jRadBtn1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn1.setText("1");

        buttonGroup.add(jRadBtn2);
        jRadBtn2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn2.setText("4");

        buttonGroup.add(jRadBtn3);
        jRadBtn3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn3.setText("2");

        buttonGroup.add(jRadBtn4);
        jRadBtn4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn4.setText("5");

        buttonGroup.add(jRadBtn5);
        jRadBtn5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn5.setText("6");
        jRadBtn5.setToolTipText("");

        buttonGroup.add(jRadBtn6);
        jRadBtn6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn6.setText("7");

        buttonGroup.add(jRadBtn7);
        jRadBtn7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn7.setText("8");

        buttonGroup.add(jRadBtn8);
        jRadBtn8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn8.setText("3");

        buttonGroup.add(jRadBtn9);
        jRadBtn9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn9.setText("9");
        jLabel1.setText("Ingredient Name: ");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jButton1.setBackground(new java.awt.Color(186, 207, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setText("Add New Ingredient!");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //allows user to search for ingredient
    }                                         

    private void searchFldActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //where the user types the input they are searching for
    }                                         

    private void addToRecipeBtnActionPerformed(java.awt.event.ActionEvent evt) {                                               
        //adds results to recipe
    }                                              

    private void typeDropDownActionPerformed(java.awt.event.ActionEvent evt) {                                             
        //dropdown for selection of quantity type
    }                                            

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        //where the user types the quantity input
    }                                             

    private void notesFieldActionPerformed(java.awt.event.ActionEvent evt) {                                           
        //where the user types notes
    }                                          
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewIngredient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewIngredient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewIngredient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewIngredient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewIngredient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
