package com.thegrocery.thegroceryfrugal.GUI;

import com.thegrocery.thegroceryfrugal.Models.Categories;
import com.thegrocery.thegroceryfrugal.Models.Ingredients;
import com.thegrocery.thegroceryfrugal.Models.Measurement;
import com.thegrocery.thegroceryfrugal.Utility.CategoryUtility;
import com.thegrocery.thegroceryfrugal.Utility.IngredientUtility;
import com.thegrocery.thegroceryfrugal.Utility.MeasurementUtility;
import java.util.Iterator;
import java.util.List;

public class NewIngredient extends javax.swing.JFrame {

    public NewIngredient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        searchTtle = new javax.swing.JLabel();
        searchFld = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        quantityLbl = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        typeLbl = new javax.swing.JLabel();
        typeDropDown = new javax.swing.JComboBox<>();
        notesLbl = new javax.swing.JLabel();
        notesField = new javax.swing.JTextField();
        addToRecipeBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jRadBtn1 = new javax.swing.JRadioButton();
        jRadBtn2 = new javax.swing.JRadioButton();
        jRadBtn3 = new javax.swing.JRadioButton();
        jRadBtn4 = new javax.swing.JRadioButton();
        jRadBtn5 = new javax.swing.JRadioButton();
        jRadBtn6 = new javax.swing.JRadioButton();
        jRadBtn7 = new javax.swing.JRadioButton();
        jRadBtn8 = new javax.swing.JRadioButton();
        jRadBtn9 = new javax.swing.JRadioButton();
        jRadBtn10 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingredients");

        searchTtle.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        searchTtle.setText("Search:");

        searchFld.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        searchFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFldActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Choose ingredient from results:");

        quantityLbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        quantityLbl.setText("Quantity:");

        quantityField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });

        typeLbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        typeLbl.setText("Quantity Type:");
        
        // Code added by Jacob
        List<Measurement> measurements = MeasurementUtility.listAllMeasurements();
        String[] types = new String[measurements.size()];
        for (int i = 0; i < measurements.size(); i++) {
            types[i] = measurements.get(i).getName();
            
        }
        
        
        typeDropDown.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        typeDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(types));
        typeDropDown.setToolTipText("");
        typeDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeDropDownActionPerformed(evt);
            }
        });

        notesLbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        notesLbl.setText("Notes:");

        notesField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        notesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesFieldActionPerformed(evt);
            }
        });

        addToRecipeBtn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        addToRecipeBtn.setText("Add to Recipe");
        addToRecipeBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addToRecipeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToRecipeBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.setNextFocusableComponent(jScrollPane1);

        buttonGroup.add(jRadBtn1);
        jRadBtn1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn1.setText("1");

        buttonGroup.add(jRadBtn2);
        jRadBtn2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn2.setText("4");

        buttonGroup.add(jRadBtn3);
        jRadBtn3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn3.setText("2");

        buttonGroup.add(jRadBtn4);
        jRadBtn4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn4.setText("5");

        buttonGroup.add(jRadBtn5);
        jRadBtn5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn5.setText("6");
        jRadBtn5.setToolTipText("");

        buttonGroup.add(jRadBtn6);
        jRadBtn6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn6.setText("7");

        buttonGroup.add(jRadBtn7);
        jRadBtn7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn7.setText("8");

        buttonGroup.add(jRadBtn8);
        jRadBtn8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn8.setText("3");

        buttonGroup.add(jRadBtn9);
        jRadBtn9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn9.setText("9");

        buttonGroup.add(jRadBtn10);
        jRadBtn10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadBtn10.setText("10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRadBtn6)
                        .addComponent(jRadBtn7)
                        .addComponent(jRadBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addComponent(jRadBtn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jRadBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadBtn9)
                    .addComponent(jRadBtn10))
                .addGap(0, 130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jRadBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadBtn3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadBtn8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadBtn4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadBtn5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadBtn6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadBtn7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadBtn9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadBtn10)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchTtle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchFld, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(quantityLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(typeLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(typeDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(notesLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(notesField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(36, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(addToRecipeBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTtle)
                    .addComponent(searchFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLbl)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notesLbl)
                    .addComponent(notesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addToRecipeBtn)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //allows user to search for ingredient
        List<Ingredients> ingredients = IngredientUtility.findIngredientsByName(this.searchFld.getText());
        for (Iterator iter = ingredients.iterator(); iter.hasNext(); ) {
            Ingredients ingredient = (Ingredients) iter.next();
            javax.swing.JRadioButton ingredient_button = new javax.swing.JRadioButton();
            ingredient_button.setText(ingredient.getName());
            this.buttonGroup.add(ingredient_button);
        }
        this.jScrollPane1.updateUI();
    }                                         

    private void searchFldActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //where the user types the input they are searching for
    }                                         

    private void addToRecipeBtnActionPerformed(java.awt.event.ActionEvent evt) {                                               
        //adds results to recipe
    }                                              

    private void typeDropDownActionPerformed(java.awt.event.ActionEvent evt) {                                             
        //dropdown for selection of quantity type
    }                                            

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        //where the user types the quantity input
    }                                             

    private void notesFieldActionPerformed(java.awt.event.ActionEvent evt) {                                           
        //where the user types notes
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewIngredient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewIngredient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewIngredient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewIngredient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewIngredient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addToRecipeBtn;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadBtn1;
    private javax.swing.JRadioButton jRadBtn10;
    private javax.swing.JRadioButton jRadBtn2;
    private javax.swing.JRadioButton jRadBtn3;
    private javax.swing.JRadioButton jRadBtn4;
    private javax.swing.JRadioButton jRadBtn5;
    private javax.swing.JRadioButton jRadBtn6;
    private javax.swing.JRadioButton jRadBtn7;
    private javax.swing.JRadioButton jRadBtn8;
    private javax.swing.JRadioButton jRadBtn9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField notesField;
    private javax.swing.JLabel notesLbl;
    private javax.swing.JTextField quantityField;
    private javax.swing.JLabel quantityLbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchFld;
    private javax.swing.JLabel searchTtle;
    private javax.swing.JComboBox<String> typeDropDown;
    private javax.swing.JLabel typeLbl;
    // End of variables declaration                   
}
