package com.thegrocery.thegroceryfrugal.Models;
// Generated Jun 1, 2019 4:17:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private int id;
     private String description;
     private Set recipes = new HashSet(0);

    public Categories() {
    }

	
    public Categories(int id) {
        this.id = id;
    }
    public Categories(int id, String description, Set recipes) {
       this.id = id;
       this.description = description;
       this.recipes = recipes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getRecipes() {
        return this.recipes;
    }
    
    public void setRecipes(Set recipes) {
        this.recipes = recipes;
    }




}


