package com.thegrocery.thegroceryfrugal.Models;
// Generated Jun 4, 2019 6:31:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nutrition generated by hbm2java
 */

@Entity
@Table(name = "nutrition")
public class Nutrition  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable=false, unique=true)
    private long id;
    
    @Column(name = "calories")
    private String calories;
    
    @Column(name = "calories_fat")
    private String caloriesFat;
    
    @Column(name = "cholesterol")
    private String cholesterol;
    
    @Column(name = "saturated_fat")
    private String saturatedFat;
    
    @Column(name = "total_fat")
    private String totalFat;
    
    @Column(name = "trans_fat")
    private String transFat;
    
    @Column(name = "sodium")
    private String sodium;
    
    @Column(name = "total_carb")
    private String totalCarb;
    
    @Column(name = "dietary_fib")
    private String dietaryFib;
    
    @Column(name = "sugars")
    private String sugars;
    
    @Column(name = "protein")
    private String protein;
    
    @OneToMany(mappedBy = "nutrition")
    private Set<Recipe> recipes = new HashSet(0);

    public Nutrition() {
    }

	
    public Nutrition(long id) {
        this.id = id;
    }
    public Nutrition(long id, String calories, String caloriesFat, String cholesterol, String saturatedFat, String totalFat, String transFat, String sodium, String totalCarb, String dietaryFib, String sugars, String protein, Set recipes) {
       this.id = id;
       this.calories = calories;
       this.caloriesFat = caloriesFat;
       this.cholesterol = cholesterol;
       this.saturatedFat = saturatedFat;
       this.totalFat = totalFat;
       this.transFat = transFat;
       this.sodium = sodium;
       this.totalCarb = totalCarb;
       this.dietaryFib = dietaryFib;
       this.sugars = sugars;
       this.protein = protein;
       this.recipes = recipes;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getCalories() {
        return this.calories;
    }
    
    public void setCalories(String calories) {
        this.calories = calories;
    }
    public String getCaloriesFat() {
        return this.caloriesFat;
    }
    
    public void setCaloriesFat(String caloriesFat) {
        this.caloriesFat = caloriesFat;
    }
    public String getCholesterol() {
        return this.cholesterol;
    }
    
    public void setCholesterol(String cholesterol) {
        this.cholesterol = cholesterol;
    }
    public String getSaturatedFat() {
        return this.saturatedFat;
    }
    
    public void setSaturatedFat(String saturatedFat) {
        this.saturatedFat = saturatedFat;
    }
    public String getTotalFat() {
        return this.totalFat;
    }
    
    public void setTotalFat(String totalFat) {
        this.totalFat = totalFat;
    }
    public String getTransFat() {
        return this.transFat;
    }
    
    public void setTransFat(String transFat) {
        this.transFat = transFat;
    }
    public String getSodium() {
        return this.sodium;
    }
    
    public void setSodium(String sodium) {
        this.sodium = sodium;
    }
    public String getTotalCarb() {
        return this.totalCarb;
    }
    
    public void setTotalCarb(String totalCarb) {
        this.totalCarb = totalCarb;
    }
    public String getDietaryFib() {
        return this.dietaryFib;
    }
    
    public void setDietaryFib(String dietaryFib) {
        this.dietaryFib = dietaryFib;
    }
    public String getSugars() {
        return this.sugars;
    }
    
    public void setSugars(String sugars) {
        this.sugars = sugars;
    }
    public String getProtein() {
        return this.protein;
    }
    
    public void setProtein(String protein) {
        this.protein = protein;
    }
    public Set getRecipes() {
        return this.recipes;
    }
    
    public void setRecipes(Set recipes) {
        this.recipes = recipes;
    }

    public void addNutrition(Recipe recipe){
        recipes.add(recipe);
        recipe.setNutrition(this);
    }
    
    public void removeNutrition(Recipe recipe){
        recipes.remove(recipe);
        recipe.setNutrition(null);
    }


}


